name       : python-shapely
version    : 1.8.1
release    : 9
source     :
    - git|https://github.com/Toblerity/Shapely : 1.8.1
homepage   : https://github.com/shapely/shapely
license    : BSD-3-Clause
component  : programming.python
summary    : Manipulation and analysis of geometric objects
description: |
    Shapely is a package for manipulation and analysis of planar geometric objects. It is based on the widely deployed GEOS (the engine of PostGIS) and JTS (from which GEOS is ported) libraries. Shapely is not concerned with data formats or coordinate systems, but can be readily integrated with packages that are.
builddeps  :
    - cython
    - geos          # check
    - numpy
    - python-pytest # check
rundeps    :
    - geos
    - numpy
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test py.test3
