name       : python-shapely
version    : 1.6.4_p2
release    : 1
source     :
    - https://pypi.io/packages/source/S/Shapely/Shapely-1.6.4.post2.tar.gz : c4b87bb61fc3de59fc1f85e71a79b0c709dc68364d9584473697aad4aa13240f
license    : BSD-3-Clause
component  : programming.python
summary    : Manipulation and analysis of geometric objects
description: |
    Shapely is a package for manipulation and analysis of planar geometric objects. It is based on the widely deployed GEOS (the engine of PostGIS) and JTS (from which GEOS is ported) libraries. Shapely is not concerned with data formats or coordinate systems, but can be readily integrated with packages that are.
builddeps  :
    - pkgconfig(python3)
    - cython
    - geos
    - numpy
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    pushd $PKG_BUILD_DIR/py3build
        #py.test3
        python setup.py test
    popd
